services:
  db:
    image: postgres:16-alpine
    container_name: pg-avaliacao
    environment:
      POSTGRES_DB: avaliacao
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d avaliacao" ]
      interval: 5s
      timeout: 3s
      retries: 10

  avaliacao:
    build:
      context: .
      dockerfile: Dockerfile
    image: avaliacao:dev
    container_name: avaliacao
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: "8084"

      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/avaliacao"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "postgres"

      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"

      EVENTS_BASE_URL: "http://host.docker.internal:8083"
    ports:
      - "8084:8084"

volumes:
  pgdata:
